
default: &default
  adapter: postgresql
  encoding: unicode



development: &development
  <<: *default
  database: todo_rails_development
  pool: 5
  username: root
  password:
  timeout: 5000

test:
  <<: *default
  database: todo_rails_test
  pool: 5
  username: root
  password:
  timeout: 5000